openapi: 3.0.1
info:
  contact:
    email: jolozanop@alumnos.unex.es
    name: JoserraLP
    url: http://spilab.es/
  description: This API provides the neccesary data for the TFG system
  termsOfService: http://spilab.es/
  title: TFG Server
  version: "1.0"
paths:
  /allowed_places_types:
    delete:
      description: This deletes the current allowed places type.
      operationId: deleteAllowedPlacesType
      parameters:
      - description: Allowed Place Type
        explode: true
        in: query
        name: type
        required: true
        schema:
          type: string
        style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Deleted
                title: Deleted
                type: string
          description: Deleted
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Delete the allowed place type.
      tags:
      - AllowedPlacesType
      x-swagger-router-controller: AllowedPlacesType
    get:
      description: Return all the allowed places types
      operationId: getAllowedPlacesType
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Return all the allowed places types
      tags:
      - AllowedPlacesType
      x-swagger-router-controller: AllowedPlacesType
    post:
      description: Addition of a new allowed place type
      operationId: postAllowedPlaceType
      requestBody:
        content:
          application/json:
            schema:
              properties:
                type:
                  type: string
                  example: restaurant
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
        409:
          content:
            text/plain:
              schema:
                example: There is a conflict
                title: Index conflict
                type: string
          description: DB index conflict
      summary: Add a new allowed place type.
      tags:
      - AllowedPlacesType
      x-swagger-router-controller: AllowedPlacesType
  /device_id:
    delete:
      description: This deletes the device ID.
      operationId: deleteDeviceID
      parameters:
      - description: Device ID
        explode: true
        in: query
        name: deviceID
        required: true
        schema:
          type: string
        style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Deleted
                title: Deleted
                type: string
          description: Deleted
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Delete the device ID.
      tags:
      - DeviceID
      x-swagger-router-controller: DeviceID
    get:
      description: Return all the devices ID
      operationId: getDeviceID
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Return all the devices ID
      tags:
      - DeviceID
      x-swagger-router-controller: DeviceID
    post:
      description: Creation of a new device ID
      operationId: postDeviceID
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
        409:
          content:
            text/plain:
              schema:
                example: There is a conflict
                title: Index conflict
                type: string
          description: DB index conflict
      summary: Add a new device ID.
      tags:
      - DeviceID
      x-swagger-router-controller: DeviceID
components:
  responses:
    201:
      content:
        text/plain:
          schema:
            example: Created
            title: Created
            type: string
      description: Created
    404:
      content:
        text/plain:
          schema:
            example: Not found
            title: Endpoint not found
            type: string
      description: Not found response
    405:
      content:
        text/plain:
          schema:
            example: The format is not valid
            title: Invalid input
            type: string
      description: Invalid input
  schemas:
    AllowedPlacesType:
      example:
        type: restaurant
        idAllowedPlacesType: 1
      properties:
        idAllowedPlacesType:
          example: 1
          format: int64
          type: integer
        type:
          example: restaurant
          type: string
      type: object
